cd
SQLLDR potas/oracle CONTROL='ulgi.ctl' LOG='log/ulgi.log'
SQLLDR potas/oracle CONTROL='oddzialy_nfz.ctl' LOG='log/oddzialy_nfz.log'
SQLLDR potas/oracle CONTROL='adresy.ctl' LOG='log/adresy.log'
SQLLDR potas/oracle CONTROL='kontakty.ctl' LOG='log/kontakty.log'
SQLLDR potas/oracle CONTROL='specjalnosci.ctl' LOG='log/specjalnosci.log'
SQLLDR potas/oracle CONTROL='uprawnienia.ctl' LOG='log/uprawnienia.log'
SQLLDR potas/oracle CONTROL='stanowiska.ctl' LOG='log/stanowiska.log'
SQLLDR potas/oracle CONTROL='karty.ctl' LOG='log/karty.log'
SQLLDR potas/oracle CONTROL='choroby.ctl' LOG='log/choroby.log'
SQLLDR potas/oracle CONTROL='placowki.ctl' LOG='log/placowki.log'
SQLLDR potas/oracle CONTROL='pracownicy.ctl' LOG='log/pracownicy.log'
SQLLDR potas/oracle CONTROL='pacjenci.ctl' LOG='log/pacjenci.log'
SQLLDR potas/oracle CONTROL='gabinety.ctl' LOG='log/gabinety.log'
SQLLDR potas/oracle CONTROL='wizyty.ctl' LOG='log/wizyty.log'
SQLLDR potas/oracle CONTROL='recepty.ctl' LOG='log/recepty.log'
SQLLDR potas/oracle CONTROL='pozycje_recept.ctl' LOG='log/pozycje_recept.log'
SQLLDR potas/oracle CONTROL='statusy_wizyt.ctl' LOG='log/statusy_wizyt.log'
SQLLDR potas/oracle CONTROL='zabiegi.ctl' LOG='log/zabiegi.log'
pause